### ISSUE TITLE
cdk8s-cli import doesn't work on Windows

### ISSUE THREAD

**Issue by PtD** [awslabs/cdk8s#182]
### Description of the bug:
When running 
**cdk8s -l python import k8s**

I get the following error:

```
Error: spawn D:\softdev\nodejs\node_modules\cdk8s-cli\node_modules\jsii\bin\jsii ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn D:\\softdev\\nodejs\\node_modules\\cdk8s-cli\\node_modules\\jsii\\bin\\jsii',
  path: 'D:\\softdev\\nodejs\\node_modules\\cdk8s-cli\\node_modules\\jsii\\bin\\jsii',
  spawnargs: [ '--silence-warnings', 'reserved-word' ]
}

```
Also, the symlink operation that is done at a previous step, requires that cdk8s should be started as Administrator, which is not very convenient.

### Reproduction Steps:
On Windows shell (cmd or PowerShell, all the same), run:
**cdk8s -l python import k8s**

### Error Log:
```
Error: spawn D:\softdev\nodejs\node_modules\cdk8s-cli\node_modules\jsii\bin\jsii ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn D:\\softdev\\nodejs\\node_modules\\cdk8s-cli\\node_modules\\jsii\\bin\\jsii',
  path: 'D:\\softdev\\nodejs\\node_modules\\cdk8s-cli\\node_modules\\jsii\\bin\\jsii',
  spawnargs: [ '--silence-warnings', 'reserved-word' ]
}
```

### Environment:

  - **Framework Version**: 0.21.0
  - **OS**: Windows 10

### Other:
N/A

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Fixed by #205
