### ISSUE TITLE
Install fails in a directory named cdk8s

### ISSUE THREAD

**Issue by SodaGremlin** [awslabs/cdk8s#235]
### Description of the bug:
When initializing a new typescript project with in a directory named cdk8s the install will fail. 

### Reproduction Steps:
1. Create `cdk8s`
2. Install the cli
3. run `cdk8s init typescript-app`

### Error Log:
$cdk8s init typescript-app
Initializing a project from the typescript-app template
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "cdk8s" under a package
npm ERR! also called "cdk8s". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/greggharrington/.npm/_logs/2020-06-11T21_23_31_796Z-debug.log
cdk8s init TYPE

Create a new cdk8s project from a template.

Positionals:
  TYPE  Project type                                                                                         [required] [choices: "python-app", "typescript-app"]

Options:
  --version        Show version number                                                                                                                  [boolean]
  --help           Show help                                                                                                                            [boolean]
  --dist           Install dependencies from a "dist" directory (for development)                                                                        [string]
  --cdk8s-version  The cdk8s version to use when creating the new project                                                            [string] [default: "0.25.0"]

Error: Command failed: npm install  cdk8s@^0.25.0 constructs@^2.0.1
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at installDeps (/Users/greggharrington/.nvm/versions/node/v12.16.0/lib/node_modules/cdk8s-cli/templates/typescript-app/.hooks.sscaff.js:34:3)
    at Object.exports.post (/Users/greggharrington/.nvm/versions/node/v12.16.0/lib/node_modules/cdk8s-cli/templates/typescript-app/.hooks.sscaff.js:13:3)
    at executePostHook (/Users/greggharrington/.nvm/versions/node/v12.16.0/lib/node_modules/cdk8s-cli/node_modules/sscaff/lib/sscaff.js:61:37)
    at Object.sscaff (/Users/greggharrington/.nvm/versions/node/v12.16.0/lib/node_modules/cdk8s-cli/node_modules/sscaff/lib/sscaff.js:28:15)
    at async Object.handler (/Users/greggharrington/.nvm/versions/node/v12.16.0/lib/node_modules/cdk8s-cli/bin/cmds/init.js:29:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 50069,
  stdout: null,
  stderr: null
}

### Environment:

  - **Framework Version**:
  - **OS**: Mac OSX 10.15.4

### Other:

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
This is a limitation of npm and I don't believe there is anything we can do about this. The error is also pretty good:

```
Refusing to install package with name "cdk8s" under a package
npm ERR! also called "cdk8s". Did you name your project the same
```

Is there anything else you think we can do to make this less painful?

**Comment by samschlegel** [comment]
`cdk8s init` could have an option to set the name of the package, and then check to see if the current folder name is `cdk8s`. If it is, then it could error out before the templating starts and suggest the use of the flag.
