### ISSUE TITLE
Cannot Import Istio CRD's due to error

### ISSUE THREAD

**Issue by RobertHorrox** [awslabs/cdk8s#267]
### Description of the bug:
When importing istio 1.5.8 crds I get a PascalCase error that fails the import

### Reproduction Steps:
curl https://raw.githubusercontent.com/istio/istio/1.5.8/manifests/base/files/crd-all.gen.yaml > istio_crds.yaml
cdk8s import istio_crds.yaml

### Error Log:
```
....
config.istio.io/attributemanifest
NOTE: Temp directory retained due to an error: /var/folders/f2/dp3vkzg520bbj33719z0gv3m0000gp/T/temp-CEQKku
Error: jsii compilation failed with non-zero exit code: 1
  | [2020-07-13T11:38:59.709] [ERROR] jsii/compiler - Type model errors prevented the JSII assembly from being created
  | error TS0: Type names must use PascalCase: attributemanifestOptions
  | error TS0: Type names must use PascalCase: attributemanifest
  +----------------------------------------------------------------------------------
  | Command: /usr/local/Cellar/cdk8s/0.26.0/libexec/lib/node_modules/cdk8s-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /var/folders/f2/dp3vkzg520bbj33719z0gv3m0000gp/T/temp-CEQKku
  +----------------------------------------------------------------------------------
    at newError (/usr/local/Cellar/cdk8s/0.26.0/libexec/lib/node_modules/cdk8s-cli/node_modules/jsii-srcmak/lib/util.js:38:20)
    at ChildProcess.<anonymous> (/usr/local/Cellar/cdk8s/0.26.0/libexec/lib/node_modules/cdk8s-cli/node_modules/jsii-srcmak/lib/util.js:55:29)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

### Environment:
- cdk8s --version  = 0.26.0
- **OS**: OSX
- Python : 3.8.3

### Other:
Project is a python CDK8s

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
@campionfellin would you be able to take a look at this?

**Comment by campionfellin** [comment]
Yep, I can take this
