### ISSUE TITLE
cdk8s import k8s -l python Error: error during project initialization: Error: Command failed   cdk8s-cli@1.0.0-beta.5

### ISSUE THREAD

**Issue by LoongLiWang** [awslabs/cdk8s#468]
### Description of the bug:

Error in executing ``` cdk8s init python-app ```

### Reproduction Steps:

cdk8s init error

### Error Log:

```bash
$ cdk8s init python-app
Initializing a project from the python-app template
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
[    ] Locking..Success!
Updated Pipfile.lock (d8ed2c)!
Installing dependencies from Pipfile.lock (d8ed2c)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing cdk8s~=1.0.0.b5...
Adding cdk8s to Pipfile's [packages]...
Installation Succeeded
Pipfile.lock (d8ed2c) out of date, updating to (5bce71)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
[==  ] Locking..Success!
Updated Pipfile.lock (5bce71)!
Installing dependencies from Pipfile.lock (5bce71)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing cdk8s-plus-17~=1.0.0.b5...
Adding cdk8s-plus-17 to Pipfile's [packages]...
Installation Succeeded
Pipfile.lock (5bce71) out of date, updating to (feac73)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
[ ===] Locking..Success!
Updated Pipfile.lock (feac73)!
Installing dependencies from Pipfile.lock (feac73)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
'C:\Users\Administrator\AppData\Roaming\npm\node_modules\cdk8s-cli\bin\cdk8s' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
Error: error during project initialization: Error: Command failed: C:\Users\Administrator\AppData\Roaming\npm\node_modules\cdk8s-cli\bin\cdk8s import k8s -l python
'C:\Users\Administrator\AppData\Roaming\npm\node_modules\cdk8s-cli\bin\cdk8s' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Object.exports.post.options [as post] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cdk8s-cli\templates\python-app\.hooks.sscaff.js:50:3)
    at executePostHook (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cdk8s-cli\node_modules\sscaff\lib\sscaff.js:61:37)
    at Object.sscaff (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cdk8s-cli\node_modules\sscaff\lib\sscaff.js:28:15)
STDOUT:

STDERR:
'C:\Users\Administrator\AppData\Roaming\npm\node_modules\cdk8s-cli\bin\cdk8s' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at Object.handler (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cdk8s-cli\lib\cli\cmds\init.js:37:19)

```

### Environment:

  - **Framework Version**: 
  - **OS**: windows 10 
  - **Python Version**:  Python 3.7.9
  - **Pipenv Version**:  pipenv, version 2020.11.15
  - **Npm Version**: 6.14.8
  - **cdk8s-cli Version**: cdk8s-cli@1.0.0-beta.5
  - **nodejs version**:  10.23.0

### Other:

--- 

This is :bug: Bug Report

**Comment by campionfellin** [comment]
Hey @LoongLiWang I think this could possibly be due to some issues with how the template scaffolding is set up. Looks like you're failing here:

https://github.com/awslabs/cdk8s/blob/1bcb66b7cce667bc85534d731a63aec0590f70c4/packages/cdk8s-cli/templates/python-app/.hooks.sscaff.js#L50-L51

Could you just run `cdk8s import k8s -l python` followed by `pipenv run main.py`?

You may also have some issues running `cdk8s synth` in which case you'll want to look at your `cdk8s.yaml` config file and make sure you have updated the `app` here to use Windows paths:

https://github.com/awslabs/cdk8s/blob/1bcb66b7cce667bc85534d731a63aec0590f70c4/packages/cdk8s-cli/templates/python-app/cdk8s.yaml#L2

Please let me know if that works for you!

**Comment by LoongLiWang** [comment]
thank， I successfully generated the dist/hello.k8s.yaml file by executing ``` pipenv run python main.py ```
```bash
Administrator@DESKTOP-KO3D33B MINGW64 /f/cdk8s/hello
$ pwd
/f/cdk8s/hello

Administrator@DESKTOP-KO3D33B MINGW64 /f/cdk8s/hello
$ pipenv run python main.py

Administrator@DESKTOP-KO3D33B MINGW64 /f/cdk8s/hello
$ ls -l dist/hello.k8s.yaml
-rw-r--r-- 1 Administrator 197121 0 12月 17 14:02 dist/hello.k8s.yaml

Administrator@DESKTOP-KO3D33B MINGW64 /f/cdk8s/hello
$
```

But the execution of  ```cdk8s import k8s -l python```  still reports an error
```bash
Administrator@DESKTOP-KO3D33B MINGW64 /f/cdk8s/hello
$ cdk8s import k8s -l python
k8s
{ Error: getaddrinfo ENOENT raw.githubusercontent.com raw.githubusercontent.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'raw.githubusercontent.com',
  host: 'raw.githubusercontent.com',
  port: 443 }

Administrator@DESKTOP-KO3D33B MINGW64 /f/cdk8s/hello
$

```
Is this a network problem?

**Comment by iliapolo** [comment]
> Is this a network problem?

@LoongLiWang looks like it...was it resolved?

**Comment by LoongLiWang** [comment]
Yes, thank you, it has been resolved, this is caused by network problems.
